### ISSUE TITLE
[Bug]: Process break in the middle, ends up in two collections

### ISSUE THREAD

**Issue by MyNameisLeon** [metaplex-foundation/collection-migration-issues#10]
### Issue description

1. start the "Create a new Collection" process on collections.metaplex.com
2. Break the process completly
3. (there was no collection in progress) so click new collection again
4. create this collection successfully

Result were two collections. One finished collection and one in progress.
Normally i guess this wouldnt be a problem at all but it ended up in to different incomplete collections in opensea.

All 2222 Nfts have the correct Collection id in metadata.

Could be also that this is an issue i should report to opensea instead.

Thanks in advance for any help 

### Collection Mint Address

5wPDgzwgpofgg6Xn2ti1BnUjiguiSs8TEAauC8pbeJ2a (Correct Collection); 5wC38eGYogVeUJTQtmLhKm1y8mvmPaCVPfMtAoSe7Khp (In Progress Colleciton) 

### Mint Address of NFT

G811jrgACLYQZSgSqqSiKo2vuNMVQ1kQZQGxKMXYzoN5

### Browser

Chrome Version 101.0.4951.54

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by roederw** [comment]
You need to wait for a migration to finish. Or start it over again. The migration service does whatever you tell it to do. Some folks do change their Collection NFT, so this is a supported scenario.

**Comment by roederw** [comment]
Looks like `5wPDgzwgpofgg6Xn2ti1BnUjiguiSs8TEAauC8pbeJ2a` was successfully migrated. Closing
