### ISSUE TITLE
[Bug]:  MIGRATION PROBLEMS

### ISSUE THREAD

**Issue by TommasoBranchi** [metaplex-foundation/collection-migration-issues#12]
### Issue description

I see the sign “your collection is still being migrated, check back soon” from 25 hours, i am on mainnet and there isn’t the transaction in transaction history of phatom wallet.
![2F40CB81-6960-4ED3-A670-4F973C714FEF](https://user-images.githubusercontent.com/103031895/174425644-4c95b169-bce6-4822-bac3-2182059954e6.jpeg)

### Mint Address of NFT

Bsy7XpgYnxemEGcGbBbPYknynjikFf5tUMry3CwiqXKJ

### Browser

Still chrome and brave last version

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by Desi0nft** [comment]
Same here! 
Since Friday the migration is stuck and a never ending message appears: Your Collection is still being migrated, check back soon…
Please advise or give us some feedback, what are the reasons and is this being troubleshooted now?

**Comment by roederw** [comment]
Taking a look.

**Comment by roederw** [comment]
Please provide the Collection NFT mint address. The address above is an account, not a mint.
