### ISSUE TITLE
[Bug]: Need to remove an NFT from the collection

### ISSUE THREAD

**Issue by SutekiNFT** [metaplex-foundation/collection-migration-issues#17]
### Issue description

I need to have a specific NFT removed from the collection. It was stolen by a scammer from a members wallet, and I have updated the metadata to reflect that so it can't be sold.

Token Address: 7owUBx2p32ampE6WEDKBwJFsP8dfP54Wqy3QFxEc6Qbp

### Collection Mint Address

6oFpup9jMs6M6Qaz5YbJXup2tSLmYW3jvtPQQcNdDke

### Mint Address of NFT

DsE16dJ1b7iFnXuPxyNkn4N9pB5WbFCwVEQWuahP1NSh

### Browser

Google Chrome

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by samuelvanderwaal** [comment]
This tool doesn't support unverifying items from collections. You can use the[ JS SDK](https://github.com/metaplex-foundation/js) to write your own code to do it, or use a tool like [Metaboss](https://github.com/samuelvanderwaal/metaboss).
