### ISSUE TITLE
[Feature]: code for creating collection

### ISSUE THREAD

**Issue by johnsonchau-bulb** [metaplex-foundation/collection-migration-issues#21]
### Feature

I'd like to see how you implement the code for creating and verifying collections so I can use it for my large set of NFTs.

### Ideal solution or implementation

An example script of creating a collection and verifying it.

**Comment by samuelvanderwaal** [comment]
Unfortunately, I don't have time to draft up an example script for you right now, but if you haven't already read [the docs on collections](https://docs.metaplex.com/programs/token-metadata/certified-collections) they will probably help you a lot. If you have a specific question about how collections work after reviewing the docs let me know.

Once you create a parent NFT, which is just a normal NFT with the optional Collection Details field set for a sized collection, you run the `set_and_verify` command on all items you want to add to the collection. All items must have the same update authority as the collection parent NFT.

You can see how [Metaboss does this as an idea](https://github.com/samuelvanderwaal/metaboss/blob/39467cbb32bfb68a8f3cb7aa0a2872f3b170ffe6/src/collections/migrate.rs#L206), but all the CLI and async stuff might obfuscate the fact that it's a simple call to `set_and_verify` to add an item to the collection.
