### ISSUE TITLE
[Bug]: Image upload leads to CORS error

### ISSUE THREAD

**Issue by boom235** [metaplex-foundation/collection-migration-issues#3]
### Issue description

Fill in all fields, I did add 4 collections by first validated creator ID, but I do not think this is needed to reproduce the problem.
I used a Logo in SVG forma
![err](https://user-images.githubusercontent.com/25117791/161728926-e2291957-1952-4769-bb9a-b33530db7707.PNG)
t

### Relevant log output

```Shell
Access to XMLHttpRequest at 'https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile' from origin 'https://collections.metaplex.com/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
us-central1-metaplex-studios.cloudfunctions.net/uploadFile:1 Failed to load resource: net::ERR_FAILED
createError.js:16 Uncaught (in promise) Error: Network Error
at e.exports (createError.js:16:15)
at XMLHttpRequest.y.onerror (xhr.js:117:14)
at XMLHttpRequest.i (helpers.ts:98:17)
e.exports @ createError.js:16
y.onerror @ xhr.js:117
i @ helpers.ts:98
instrument.ts:154 GET https://2d5hc1e0ri.execute-api.us-east-1.amazonaws.com/get-collections?authority=62iJafu9kn3TGBxkYAA7XtoAvUYKoAvsaiuAmAMPSsLX 404
(anonymous) @ instrument.ts:154
(anonymous) @ fetchCollections.ts:27
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ fetchCollections.ts:19
i @ Home.tsx:27
(anonymous) @ Home.tsx:41
Ls @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Ns @ react-dom.production.min.js:261
gs @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Xi @ react-dom.production.min.js:123
Gi @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Zt @ react-dom.production.min.js:73
i @ helpers.ts:98
instrument.ts:125 Transaction simulation failed: Error processing Instruction 5: custom program error: 0xc
Program 11111111111111111111111111111111 invoke [1]
Program 11111111111111111111111111111111 success
Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr invoke [1]
Program log: Memo (len 64): "e2ffa79412bcd8bc92915b33cf6cc1a560f22daf212dfcb0e5d0dad5c4655340"
Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr consumed 24164 of 200000 compute units
Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr success
Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr invoke [1]
Program log: Memo (len 64): "a8c3fe15e8933f618eb62e67acc21baa73f6d539aa9465ed14468a6eca29af55"
Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr consumed 24164 of 200000 compute units
Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr success
Program 11111111111111111111111111111111 invoke [1]
Program 11111111111111111111111111111111 success
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
Program log: Instruction: InitializeMint
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2457 of 200000 compute units
Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
Program log: Instruction: Create Metadata Accounts v2
Program log: Transfer 5616720 lamports to the new account
Program 11111111111111111111111111111111 invoke [2]
Program 11111111111111111111111111111111 success
Program log: Allocate space for the account
Program 11111111111111111111111111111111 invoke [2]
Program 11111111111111111111111111111111 success
Program log: Assign the account to the owning program
Program 11111111111111111111111111111111 invoke [2]
Program 11111111111111111111111111111111 success
Program log: Symbol too long
Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 20246 of 200000 compute units
Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: custom program error: 0xc
(anonymous) @ instrument.ts:125
overrideMethod @ react_devtools_backend.js:3973
(anonymous) @ connection.ts:3961
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ 2.41404da4.chunk.js:2
(anonymous) @ connection.ts:3921
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ 2.41404da4.chunk.js:2
(anonymous) @ transactions.ts:29
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
o @ 2.41404da4.chunk.js:2
Promise.then (async)
s @ 2.41404da4.chunk.js:2
o @ 2.41404da4.chunk.js:2
Promise.then (async)
s @ 2.41404da4.chunk.js:2
(anonymous) @ 2.41404da4.chunk.js:2
_ @ 2.41404da4.chunk.js:2
H @ transactions.ts:20
(anonymous) @ mintCollectionNFT.ts:228
value @ pipeline.ts:19
(anonymous) @ mintCollectionNFT.ts:226
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
g @ mintCollectionNFT.ts:43
(anonymous) @ initCollection.ts:47
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ initCollection.ts:22
(anonymous) @ init.ts:43
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ init.ts:28
lt @ createEffect.ts:156
(anonymous) @ createEffect.ts:80
b @ kernel.ts:396
l @ kernel.ts:301
n.create @ createEffect.ts:131
e @ createUnit.ts:151
(anonymous) @ submit.ts:73
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ submit.ts:58
lt @ createEffect.ts:156
(anonymous) @ createEffect.ts:80
b @ kernel.ts:396
l @ kernel.ts:301
n.create @ createEffect.ts:131
e @ createUnit.ts:151
(anonymous) @ CreateCollection.state.ts:167
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ CreateCollection.state.ts:166
lt @ createEffect.ts:156
(anonymous) @ createEffect.ts:80
b @ kernel.ts:396
l @ kernel.ts:301
n.create @ createEffect.ts:131
e @ createUnit.ts:151
(anonymous) @ createFormControl.ts:1039
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ createFormControl.ts:1010
Ve @ react-dom.production.min.js:52
Xe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Ar @ react-dom.production.min.js:100
Mr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Be @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Nr @ react-dom.production.min.js:105
$t @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Zt @ react-dom.production.min.js:73
Show 65 more frames
connection.ts:3964 Uncaught (in promise) Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 5: custom program error: 0xc
at n. (connection.ts:3964:13)
at l (runtime.js:63:40)
at Generator._invoke (runtime.js:294:22)
at Generator.next (runtime.js:119:21)
at r (asyncToGenerator.js:3:20)
at u (asyncToGenerator.js:25:9)
```

### Collection Mint Address

AumgdQA7eNmMMDsSZ4TTWBHJP1b6WBeEHherZmckbeb8

### Mint Address of NFT

5VZY76vhKtZhERnoJvRLnUSSW9dUrisX7eJSKrhCHG1H

### Browser

Google Chrome latest

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by boom235** [comment]
Access to XMLHttpRequest at 'https://us-central1-metaplex-studios.cloudfunctions.net/uploadFile' from origin 'https://collections.metaplex.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
us-central1-metaplex-studios.cloudfunctions.net/uploadFile:1          Failed to load resource: net::ERR_FAILED
createError.js:16 Uncaught (in promise) Error: Network Error
    at e.exports (createError.js:16:15)
    at XMLHttpRequest.y.onerror (xhr.js:117:14)
    at XMLHttpRequest.i (helpers.ts:98:17)
e.exports @ createError.js:16
y.onerror @ xhr.js:117
i @ helpers.ts:98
instrument.ts:154          GET https://2d5hc1e0ri.execute-api.us-east-1.amazonaws.com/get-collections?authority=62iJafu9kn3TGBxkYAA7XtoAvUYKoAvsaiuAmAMPSsLX 404
(anonymous) @ instrument.ts:154
(anonymous) @ fetchCollections.ts:27
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ fetchCollections.ts:19
i @ Home.tsx:27
(anonymous) @ Home.tsx:41
Ls @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Ns @ react-dom.production.min.js:261
gs @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Xi @ react-dom.production.min.js:123
Gi @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Zt @ react-dom.production.min.js:73
i @ helpers.ts:98
instrument.ts:125 Transaction simulation failed: Error processing Instruction 5: custom program error: 0xc 
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr invoke [1]
    Program log: Memo (len 64): "e2ffa79412bcd8bc92915b33cf6cc1a560f22daf212dfcb0e5d0dad5c4655340"
    Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr consumed 24164 of 200000 compute units
    Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr success
    Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr invoke [1]
    Program log: Memo (len 64): "a8c3fe15e8933f618eb62e67acc21baa73f6d539aa9465ed14468a6eca29af55"
    Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr consumed 24164 of 200000 compute units
    Program MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr success
    Program 11111111111111111111111111111111 invoke [1]
    Program 11111111111111111111111111111111 success
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]
    Program log: Instruction: InitializeMint
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2457 of 200000 compute units
    Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success
    Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]
    Program log: Instruction: Create Metadata Accounts v2
    Program log: Transfer 5616720 lamports to the new account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Allocate space for the account
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Assign the account to the owning program
    Program 11111111111111111111111111111111 invoke [2]
    Program 11111111111111111111111111111111 success
    Program log: Symbol too long
    Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 20246 of 200000 compute units
    Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: custom program error: 0xc
(anonymous) @ instrument.ts:125
overrideMethod @ react_devtools_backend.js:3973
(anonymous) @ connection.ts:3961
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ 2.41404da4.chunk.js:2
(anonymous) @ connection.ts:3921
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ 2.41404da4.chunk.js:2
(anonymous) @ transactions.ts:29
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
o @ 2.41404da4.chunk.js:2
Promise.then (async)
s @ 2.41404da4.chunk.js:2
o @ 2.41404da4.chunk.js:2
Promise.then (async)
s @ 2.41404da4.chunk.js:2
(anonymous) @ 2.41404da4.chunk.js:2
_ @ 2.41404da4.chunk.js:2
H @ transactions.ts:20
(anonymous) @ mintCollectionNFT.ts:228
value @ pipeline.ts:19
(anonymous) @ mintCollectionNFT.ts:226
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
g @ mintCollectionNFT.ts:43
(anonymous) @ initCollection.ts:47
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ initCollection.ts:22
(anonymous) @ init.ts:43
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ init.ts:28
lt @ createEffect.ts:156
(anonymous) @ createEffect.ts:80
b @ kernel.ts:396
l @ kernel.ts:301
n.create @ createEffect.ts:131
e @ createUnit.ts:151
(anonymous) @ submit.ts:73
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ submit.ts:58
lt @ createEffect.ts:156
(anonymous) @ createEffect.ts:80
b @ kernel.ts:396
l @ kernel.ts:301
n.create @ createEffect.ts:131
e @ createUnit.ts:151
(anonymous) @ CreateCollection.state.ts:167
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ CreateCollection.state.ts:166
lt @ createEffect.ts:156
(anonymous) @ createEffect.ts:80
b @ kernel.ts:396
l @ kernel.ts:301
n.create @ createEffect.ts:131
e @ createUnit.ts:151
(anonymous) @ createFormControl.ts:1039
l @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
u @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
u @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ createFormControl.ts:1010
Ve @ react-dom.production.min.js:52
Xe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Ar @ react-dom.production.min.js:100
Mr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Be @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Nr @ react-dom.production.min.js:105
$t @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
qi @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Zt @ react-dom.production.min.js:73
Show 65 more frames
connection.ts:3964 Uncaught (in promise) Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 5: custom program error: 0xc
    at n.<anonymous> (connection.ts:3964:13)
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:25:9)

**Comment by roederw** [comment]
What is the size of the SVG you're using?

**Comment by roederw** [comment]
Also, what is the `SYMBOL` entry you're using?

**Comment by roederw** [comment]
I see this issue `Program log: Symbol too long`
