### ISSUE TITLE
[Bug]: Unable to migrate collection

### ISSUE THREAD

**Issue by kienpanthera** [metaplex-foundation/collection-migration-issues#9]
### Issue description

1. Start expand our collection.
2. After sometime the migration stop with message "We are unable to migrate this collection."
3.
<img width="1426" alt="Screen Shot 2022-05-18 at 14 26 50" src="https://user-images.githubusercontent.com/91553657/168981917-f9057695-61b0-4241-9da6-3683c1f2a743.png">
 

### Collection Mint Address

XXvLhyHFR8M2er6ZSUxjX9j8qWaXcvAx5DgawosUX8v

### Mint Address of NFT

6U8sfSRLHLoH65rCi68GHyamcdVsvoxVtEPEjRx3JP9s

### Browser

Brave

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by roederw** [comment]
Still broken? Seems to have been migrated.

**Comment by roederw** [comment]
I am adding better validation so you can't get into these states. All the `update_authorities` much match. If not, you cannot migrate your collection.
